<option value="none" selected>None</option>
<option value="Barrier">Barrier</option>
<option value="Cleanse">Cleanse</option>
<option value="Exhaust">Exhaust</option>
<option value="Flash">Flash</option>
<option value="Ghost">Ghost</option>
<option value="Heal">Heal</option>
<option value="Ignite">Ignite</option>
<option value="Revive">Revive</option>
<option value="Smite">Smite</option>
<option value="Teleport">Teleport</option>